export type FarmRecord = {
  id?: string; // Optional because it's generated by Firestore
  cropType: string;
  plantingDate: string;
  area: number;
  expenses: number;
  inputsUsed: string;
  harvestQuantity: number;
  harvestDate: string;
  marketPrice: number; // Price per unit of harvest
  farmerId: string;
};

export type FarmRecordWithProfit = FarmRecord & {
  id: string; // Guaranteed to exist when fetched
  revenue: number;
  profit: number;
};

export type Farmer = {
  id: string;
  name: string;
  farmLocation: string;
  totalArea: number;
  cropCount: number;
};