// This file is automatically generated.
// Please do not edit this file manually.

// This file was generated by Firebase Studio.
// You can copy and paste this directly into your main application
// but make sure to protect your secrets by using environment variables.
//
// You can get your configuration from the Firebase console.

export const firebaseConfig = {
  apiKey: process.env.NEXT_PUBLIC_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_APP_ID,
};
